### PR TITLE
Update: Key Injection Readme

### PR DESCRIPTION
**Pull request by hitchho**
This PR adds a comprehensive Readme file explaining the key injection process in Polkadot nodes using an Ansible script. The Readme file provides essential information about different key types, their purposes, and the step-by-step process of key injection in Polkadot nodes. This documentation will be helpful for users who are looking to set up and configure a node in the Polkadot network.

### CODE REVIEW

**Comment by BulatSaif** [comment]
Thank you, @hitchhooker, for your contribution. Your documentation is very helpful. However, I would suggest adding a note about the security considerations when using an Ansible role for managing the session key. This is important to address any potential misconceptions regarding the recommended way to manage keys on Polkadot.

Instead of assuming that this method is the recommended approach, it would be beneficial to mention that the recommended way to manage keys on Polkadot is by calling the [author_rotateKeys](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#generating-the-session-keys) RPC method. It's important to highlight that using an Ansible role for managing the session key is possible, but it requires careful attention to security.

For Testnets, managing the session key with Ansible is a common practice. However, when it comes to Mainnet, I would recommend paying closer attention to the following security considerations before using this role:

Secure storage of keys in Ansible variables: Ensure that keys are stored in Ansible variables in an encrypted format. This helps protect them from unauthorized access.

Unique keys for each node: It is crucial to avoid applying the same session key to multiple nodes. If two nodes share the same session key, they can be perceived as malicious, potentially leading to penalties such as being declared as a child or even being slashed.

By including this note about the security considerations, readers will be better informed about the recommended approach and the necessary precautions when using an Ansible role for managing the session key on Polkadot.

**Comment by stojanov-igor** [comment]
The pull request has been stale for more than a year. 

@hitchhooker Can you add the notes that @BulatSaif  is asking for?

**Comment by hitchho** [comment]
Thank you for notifying. I had completely missed the reply here. Will take a look on it.

**Review by BulatSaif — APPROVED** [review]

**Comment by BulatSaif** [comment]
@hitchhooker,  Thank you for your contribution!

**Pull request merged**
